In [2]:
import torch

In [6]:
x = torch.empty(2,2)
x

tensor([[-8.6433e+15,  3.1525e-41],
        [ 0.0000e+00,  0.0000e+00]])

In [5]:
x = torch.rand(2,2)
x

tensor([[0.3090, 0.9028],
        [0.7395, 0.0161]])

In [13]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [14]:
print(x.size())
print(x.dtype)
peinr(

torch.Size([2, 2])
torch.float32


In [17]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

### Basic operation with Tensors

In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y
print(z)
z = torch.add(x,y)
print(z)
y.add_(x) # Modify the y!!!
print(y)

tensor([[1.0518, 0.8527],
        [1.4386, 0.5527]])
tensor([[1.0518, 0.8527],
        [1.4386, 0.5527]])
tensor([[1.0518, 0.8527],
        [1.4386, 0.5527]])


In [21]:
z = x-y
z

tensor([[-0.2012, -0.4596],
        [-0.7239, -0.1845]])

In [23]:
z = x*y
z

tensor([[0.8946, 0.3352],
        [1.0283, 0.2036]])

In [24]:
z = x/y
z

tensor([[0.8087, 0.4610],
        [0.4968, 0.6663]])

In [30]:
x = torch.rand(5,3)
print(x)
print(x[:,0]) # get all Rows but only the collumn zero
print(x[0,:]) # get all Collumn but only the Row 0
print(x[1,1]) # get one element

tensor([[0.0376, 0.9411, 0.8936],
        [0.3231, 0.1507, 0.5356],
        [0.5002, 0.7505, 0.8335],
        [0.5705, 0.4134, 0.7955],
        [0.8993, 0.9822, 0.4928]])
tensor([0.0376, 0.3231, 0.5002, 0.5705, 0.8993])
tensor([0.0376, 0.9411, 0.8936])
tensor(0.1507)


### Reshaping

In [31]:
x = torch.rand(4,4)
print(x)

tensor([[0.4155, 0.1964, 0.8289, 0.0484],
        [0.5592, 0.7164, 0.1406, 0.1738],
        [0.3223, 0.8165, 0.8707, 0.8817],
        [0.8707, 0.9714, 0.2400, 0.1325]])


In [40]:
x.view(16)

tensor([0.4155, 0.1964, 0.8289, 0.0484, 0.5592, 0.7164, 0.1406, 0.1738, 0.3223,
        0.8165, 0.8707, 0.8817, 0.8707, 0.9714, 0.2400, 0.1325])

In [42]:
import numpy as np

In [44]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
