## Gradient Calculation with Autograd

In [1]:
import torch

In [29]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x + 2
print(y)
z = y*y*2
z = z.mean()
print(z)

z.backward() # dz/dx

x.grad

tensor([-0.7174, -0.1713,  0.9852], requires_grad=True)
tensor([1.2826, 1.8287, 2.9852], grad_fn=<AddBackward0>)
tensor(9.2672, grad_fn=<MeanBackward0>)


tensor([1.7101, 2.4382, 3.9803])